using Microsoft.Data.SqlClient;
namespace Shoppet_VetClinic.Services;

public sealed class OwnerCareService(IConfiguration configuration,AuthService auth)
{
    public int Actor => auth.IsPetOwner ? auth.CurrentUser?.Id ?? throw new UnauthorizedAccessException() : throw new UnauthorizedAccessException("Pet Owner account required.");
    SqlConnection Open(){var c=new SqlConnection(configuration.GetConnectionString("ShoppetDb"));c.Open();return c;}
    public List<CareContact> Contacts(){using var c=Open();using var q=new SqlCommand("SELECT Id,Name,ISNULL(Role,''),ISNULL(Address,''),ISNULL(Phone,'') FROM EmergencyContacts WHERE UserId=@U ORDER BY Name",c);q.Parameters.AddWithValue("@U",Actor);using var r=q.ExecuteReader();var rows=new List<CareContact>();while(r.Read())rows.Add(new(){Id=r.GetInt32(0),Name=r.GetString(1),Role=r.GetString(2),Address=r.GetString(3),Phone=r.GetString(4)});return rows;}
    public void SaveContact(CareContact x){if(string.IsNullOrWhiteSpace(x.Name)||x.Name.Length>150||x.Phone.Length>50)throw new ArgumentException("Enter a name and valid phone number.");Execute(x.Id==0?"INSERT INTO EmergencyContacts(UserId,Name,Role,Address,Phone,IsEmergency) VALUES(@U,@Name,@Role,@Address,@Phone,1)":"UPDATE EmergencyContacts SET Name=@Name,Role=@Role,Address=@Address,Phone=@Phone WHERE Id=@Id AND UserId=@U",("@Id",x.Id),("@Name",x.Name.Trim()),("@Role",x.Role),("@Address",x.Address),("@Phone",x.Phone));}
    public void DeleteContact(int id)=>Execute("DELETE FROM EmergencyContacts WHERE Id=@Id AND UserId=@U",("@Id",id));
    public List<CareVisit> Visits(){using var c=Open();using var q=new SqlCommand("SELECT v.Id,v.PetId,v.ClinicName,v.VisitAt,v.Purpose,v.Notes,v.Completed,p.PetName FROM VetVisitReminders v JOIN PetProfiles p ON p.Id=v.PetId WHERE v.UserId=@U AND p.UserId=@U ORDER BY v.VisitAt",c);q.Parameters.AddWithValue("@U",Actor);using var r=q.ExecuteReader();var rows=new List<CareVisit>();while(r.Read())rows.Add(new(){Id=r.GetInt32(0),PetId=r.GetInt32(1),ClinicName=r.IsDBNull(2)?"":r.GetString(2),VisitAt=r.GetDateTime(3),Purpose=r.IsDBNull(4)?"":r.GetString(4),Notes=r.IsDBNull(5)?"":r.GetString(5),Completed=r.GetBoolean(6),PetName=r.GetString(7)});return rows;}
    public void SaveVisit(CareVisit x){if(x.PetId<=0||x.ClinicName.Length>150||x.Notes.Length>1000)throw new ArgumentException("Choose a pet and keep notes under 1,000 characters.");using var c=Open();using var check=new SqlCommand("SELECT COUNT(1) FROM PetProfiles WHERE Id=@Id AND UserId=@U",c);check.Parameters.AddWithValue("@Id",x.PetId);check.Parameters.AddWithValue("@U",Actor);if(Convert.ToInt32(check.ExecuteScalar())!=1)throw new UnauthorizedAccessException();Execute(x.Id==0?"INSERT INTO VetVisitReminders(UserId,PetId,ClinicName,VisitAt,Purpose,Notes,Completed) VALUES(@U,@Pet,@Clinic,@At,@Purpose,@Notes,@Done)":"UPDATE VetVisitReminders SET PetId=@Pet,ClinicName=@Clinic,VisitAt=@At,Purpose=@Purpose,Notes=@Notes,Completed=@Done WHERE Id=@Id AND UserId=@U",("@Id",x.Id),("@Pet",x.PetId),("@Clinic",x.ClinicName),("@At",x.VisitAt),("@Purpose",x.Purpose),("@Notes",x.Notes),("@Done",x.Completed));}
    public void DeleteVisit(int id)=>Execute("DELETE FROM VetVisitReminders WHERE Id=@Id AND UserId=@U",("@Id",id));
    public SocialPreferences Social(){using var c=Open();using var q=new SqlCommand("SELECT ISNULL(FacebookUrl,''),ISNULL(InstagramUrl,''),ISNULL(OtherSocialUrl,''),ISNULL(ShowSocialLinksOnMarketplace,1),ISNULL(ShowMobileOnPublicPetId,0) FROM UserAccounts WHERE Id=@U",c);q.Parameters.AddWithValue("@U",Actor);using var r=q.ExecuteReader();return r.Read()?new(){Facebook=r.GetString(0),Instagram=r.GetString(1),Other=r.GetString(2),ShowSocial=r.GetBoolean(3),ShowPhone=r.GetBoolean(4)}:new();}
    public void SaveSocial(SocialPreferences x){foreach(var url in new[]{x.Facebook,x.Instagram,x.Other})if(!string.IsNullOrWhiteSpace(url)&&(!Uri.TryCreate(url,UriKind.Absolute,out var u)||u.Scheme!="https"||url.Length>300))throw new ArgumentException("Social links must be complete HTTPS URLs.");Execute("UPDATE UserAccounts SET FacebookUrl=@F,InstagramUrl=@I,OtherSocialUrl=@O,ShowSocialLinksOnMarketplace=@S,ShowMobileOnPublicPetId=@P WHERE Id=@U",("@F",x.Facebook.Trim()),("@I",x.Instagram.Trim()),("@O",x.Other.Trim()),("@S",x.ShowSocial),("@P",x.ShowPhone));}
    public List<(string Name,string Url)> SellerSocial(int id){using var c=Open();using var q=new SqlCommand("SELECT FacebookUrl,InstagramUrl,OtherSocialUrl FROM UserAccounts WHERE Id=@Id AND ShowSocialLinksOnMarketplace=1",c);q.Parameters.AddWithValue("@Id",id);using var r=q.ExecuteReader();var links=new List<(string,string)>();if(r.Read())for(var i=0;i<3;i++)if(!r.IsDBNull(i)&&Uri.TryCreate(r.GetString(i),UriKind.Absolute,out var u)&&u.Scheme=="https")links.Add((new[]{"Facebook","Instagram","Social profile"}[i],u.AbsoluteUri));return links;}
    public string? PublicPhone(int id){using var c=Open();using var q=new SqlCommand("SELECT MobileNumber FROM UserAccounts WHERE Id=@Id AND ShowMobileOnPublicPetId=1",c);q.Parameters.AddWithValue("@Id",id);return q.ExecuteScalar() as string;}
    public List<CareConversation> Inbox(){using var c=Open();using var q=new SqlCommand(@"SELECT CASE WHEN v.User1Id=@U THEN v.User2Id ELSE v.User1Id END,u.FullName,CASE WHEN v.User1Id=@U THEN v.User1UnreadCount ELSE v.User2UnreadCount END,v.LastUpdated FROM Conversations v JOIN UserAccounts u ON u.Id=CASE WHEN v.User1Id=@U THEN v.User2Id ELSE v.User1Id END WHERE v.User1Id=@U OR v.User2Id=@U ORDER BY v.LastUpdated DESC",c);q.Parameters.AddWithValue("@U",Actor);using var r=q.ExecuteReader();var rows=new List<CareConversation>();while(r.Read())rows.Add(new(){ContactId=r.GetInt32(0),Name=r.GetString(1),Unread=r.GetInt32(2),Updated=r.GetDateTime(3)});return rows;}
    public string ContactName(int id){using var c=Open();using var q=new SqlCommand("SELECT FullName FROM UserAccounts WHERE Id=@Id AND Role IN('Pet Owner','PetOwner')",c);q.Parameters.AddWithValue("@Id",id);return q.ExecuteScalar() as string ?? "Pet owner";}
    public List<CareMessage> Messages(int contact){var rows=new List<CareMessage>();using var c=Open();using var q=new SqlCommand("SELECT Id,SenderId,[Text],[Timestamp],ListingId FROM Messages WHERE (SenderId=@U AND ReceiverId=@Contact) OR (ReceiverId=@U AND SenderId=@Contact) ORDER BY [Timestamp],Id",c);q.Parameters.AddWithValue("@U",Actor);q.Parameters.AddWithValue("@Contact",contact);using(var r=q.ExecuteReader())while(r.Read())rows.Add(new(){Id=r.GetInt32(0),SenderId=r.GetInt32(1),Text=r.GetString(2),SentAt=r.GetDateTime(3),ListingId=r.IsDBNull(4)?null:r.GetInt32(4)});Execute("UPDATE Messages SET IsRead=1 WHERE ReceiverId=@U AND SenderId=@Contact; UPDATE Conversations SET User1UnreadCount=CASE WHEN User1Id=@U THEN 0 ELSE User1UnreadCount END,User2UnreadCount=CASE WHEN User2Id=@U THEN 0 ELSE User2UnreadCount END WHERE (User1Id=@U AND User2Id=@Contact) OR (User2Id=@U AND User1Id=@Contact)",("@Contact",contact));return rows;}
    public void Send(int contact,string text,int? listing){if(contact==Actor||contact<=0||string.IsNullOrWhiteSpace(text)||text.Length>1000)throw new ArgumentException("Enter a message of 1–1,000 characters for another pet owner.");using var c=Open();using var tx=c.BeginTransaction(System.Data.IsolationLevel.Serializable);using var q=new SqlCommand(@"IF NOT EXISTS(SELECT 1 FROM UserAccounts WHERE Id=@Contact AND Role IN('Pet Owner','PetOwner')) THROW 51000,'Pet owner not found.',1;
    DECLARE @Low INT=CASE WHEN @U<@Contact THEN @U ELSE @Contact END,@High INT=CASE WHEN @U<@Contact THEN @Contact ELSE @U END;
    IF NOT EXISTS(SELECT 1 FROM Conversations WITH(UPDLOCK,HOLDLOCK) WHERE User1Id=@Low AND User2Id=@High) INSERT INTO Conversations(User1Id,User2Id) VALUES(@Low,@High);
    DECLARE @Conversation INT=(SELECT Id FROM Conversations WHERE User1Id=@Low AND User2Id=@High);
    INSERT INTO Messages(ConversationId,SenderId,ReceiverId,ListingId,[Text]) VALUES(@Conversation,@U,@Contact,@Listing,@Text);
    UPDATE Conversations SET LastUpdated=SYSDATETIME(),User1UnreadCount=User1UnreadCount+CASE WHEN User1Id=@Contact THEN 1 ELSE 0 END,User2UnreadCount=User2UnreadCount+CASE WHEN User2Id=@Contact THEN 1 ELSE 0 END WHERE Id=@Conversation;",c,tx);q.Parameters.AddWithValue("@U",Actor);q.Parameters.AddWithValue("@Contact",contact);q.Parameters.AddWithValue("@Listing",(object?)listing??DBNull.Value);q.Parameters.AddWithValue("@Text",text.Trim());q.ExecuteNonQuery();tx.Commit();}
    void Execute(string sql,params (string Name,object Value)[] args){using var c=Open();using var q=new SqlCommand(sql,c);q.Parameters.AddWithValue("@U",Actor);foreach(var a in args)q.Parameters.AddWithValue(a.Name,a.Value);q.ExecuteNonQuery();}
}
public class CareContact {public int Id{get;set;} public string Name{get;set;}="";public string Role{get;set;}="";public string Address{get;set;}="";public string Phone{get;set;}="";}
public class CareVisit {public int Id{get;set;}public int PetId{get;set;}public string PetName{get;set;}="";public string ClinicName{get;set;}="";public DateTime VisitAt{get;set;}=DateTime.Now.AddDays(1);public string Purpose{get;set;}="";public string Notes{get;set;}="";public bool Completed{get;set;}}
public class SocialPreferences {public string Facebook{get;set;}="";public string Instagram{get;set;}="";public string Other{get;set;}="";public bool ShowSocial{get;set;}=true;public bool ShowPhone{get;set;}}
public class CareConversation {public int ContactId{get;set;}public string Name{get;set;}="";public int Unread{get;set;}public DateTime Updated{get;set;}}
public class CareMessage {public int Id{get;set;}public int SenderId{get;set;}public string Text{get;set;}="";public DateTime SentAt{get;set;}public int? ListingId{get;set;}}
