using Microsoft.Data.SqlClient;
namespace Shoppet_VetClinic.Services;
public class PetCareService(IConfiguration configuration,AuthService auth)
{
 SqlConnection Open(int pet){if(!auth.IsPetOwner||auth.CurrentUser is null)throw new UnauthorizedAccessException();var c=new SqlConnection(configuration.GetConnectionString("ShoppetDb"));c.Open();using var q=new SqlCommand("SELECT COUNT(1) FROM PetProfiles WHERE Id=@Id AND UserId=@U",c);q.Parameters.AddWithValue("@Id",pet);q.Parameters.AddWithValue("@U",auth.CurrentUser.Id);if(Convert.ToInt32(q.ExecuteScalar())!=1){c.Dispose();throw new UnauthorizedAccessException();}return c;}
 static DateTime? ParseDate(object? v) => v is DateTime dt ? dt : (v is string s && DateTime.TryParse(s, out var d) ? d : null);
 public List<CareHealth> Health(int pet){using var c=Open(pet);using var q=new SqlCommand("SELECT Id,RecordType,Title,ISNULL(Notes,''),RecordDate,NextDueDate,ISNULL(VetName,''),Completed,DateAdministered,ValidityInterval,ISNULL(ValidityUnit,'Months'),MedicationIntervalHours,TimeStarted,DosageTotal,DosageRemaining,CheckupDate,ISNULL(DocumentPaths,'') FROM PetHealthRecords WHERE PetId=@Pet ORDER BY RecordDate DESC,Id DESC",c);q.Parameters.AddWithValue("@Pet",pet);using var r=q.ExecuteReader();var list=new List<CareHealth>();while(r.Read())list.Add(new(){Id=r.GetInt32(0),Type=r.GetString(1),Title=r.GetString(2),Notes=r.GetString(3),RecordDate=r.GetDateTime(4),DueDate=r.IsDBNull(5)?null:r.GetDateTime(5),VetName=r.GetString(6),Completed=r.GetBoolean(7),DateAdministered=r.IsDBNull(8)?null:r.GetDateTime(8),ValidityInterval=r.GetInt32(9),ValidityUnit=r.GetString(10),MedicationIntervalHours=r.IsDBNull(11)?0m:Convert.ToDecimal(r.GetValue(11)),TimeStarted=r.IsDBNull(12)?null:ParseDate(r.GetValue(12)),DosageTotal=r.GetInt32(13),DosageRemaining=r.GetInt32(14),CheckupDate=r.IsDBNull(15)?null:r.GetDateTime(15),DocumentPaths=r.GetString(16)});return list;}
 public void SaveHealth(int pet,CareHealth x)
 {
    if(string.IsNullOrWhiteSpace(x.Title)||x.Title.Length>150||x.Notes.Length>1000||x.DosageTotal<0||x.DosageRemaining<0||x.DosageRemaining>x.DosageTotal||x.MedicationIntervalHours<0||x.ValidityInterval<0)throw new ArgumentException("Enter a title and valid nonnegative care values. Remaining doses cannot exceed total doses.");
    using var c=Open(pet);using var tx=c.BeginTransaction(System.Data.IsolationLevel.Serializable);
    if(x.Id==0){using var limit=new SqlCommand("SELECT COUNT(1) FROM PetHealthRecords WITH(UPDLOCK,HOLDLOCK) WHERE PetId=@Pet",c,tx);limit.Parameters.AddWithValue("@Pet",pet);if(!auth.IsPremium&&Convert.ToInt32(limit.ExecuteScalar())>=5)throw new ArgumentException("Free accounts can save 5 health records per pet. Premium is ₱150 for 2 months.");}
    using var q=new SqlCommand(x.Id==0?@"INSERT INTO PetHealthRecords(PetId,RecordType,Title,Notes,RecordDate,NextDueDate,VetName,Completed,CompletedAt,DateAdministered,ValidityInterval,ValidityUnit,MedicationIntervalHours,TimeStarted,DosageTotal,DosageRemaining,CheckupDate,DocumentPaths) VALUES(@Pet,@Type,@Title,@Notes,@At,@Due,@Vet,@Done,CASE WHEN @Done=1 THEN SYSDATETIME() ELSE NULL END,@Admin,@Validity,@Unit,@Interval,@Start,@Total,@Remaining,@Check,@Docs)":@"UPDATE PetHealthRecords SET RecordType=@Type,Title=@Title,Notes=@Notes,RecordDate=@At,NextDueDate=@Due,VetName=@Vet,Completed=@Done,CompletedAt=CASE WHEN @Done=1 THEN ISNULL(CompletedAt,SYSDATETIME()) ELSE NULL END,DateAdministered=@Admin,ValidityInterval=@Validity,ValidityUnit=@Unit,MedicationIntervalHours=@Interval,TimeStarted=@Start,DosageTotal=@Total,DosageRemaining=@Remaining,CheckupDate=@Check,DocumentPaths=@Docs WHERE Id=@Id AND PetId=@Pet",c,tx);
    Bind(q,("@Id",x.Id),("@Pet",pet),("@Type",x.Type),("@Title",x.Title.Trim()),("@Notes",x.Notes),("@At",x.RecordDate),("@Due",x.DueDate),("@Vet",x.VetName),("@Done",x.Completed),("@Admin",x.DateAdministered),("@Validity",x.ValidityInterval),("@Unit",x.ValidityUnit),("@Interval",x.MedicationIntervalHours),("@Start",x.TimeStarted),("@Total",x.DosageTotal),("@Remaining",x.DosageRemaining),("@Check",x.CheckupDate),("@Docs",x.DocumentPaths));q.ExecuteNonQuery();tx.Commit();
 }
 public void DeleteHealth(int pet,int id)=>Execute(pet,"DELETE FROM PetHealthRecords WHERE Id=@Id AND PetId=@Pet",("@Id",id));
 public void Dose(int pet,int id)=>Execute(pet,"UPDATE PetHealthRecords SET DosageRemaining=DosageRemaining-1,Completed=CASE WHEN DosageRemaining=1 THEN 1 ELSE Completed END,CompletedAt=CASE WHEN DosageRemaining=1 THEN SYSDATETIME() ELSE CompletedAt END WHERE Id=@Id AND PetId=@Pet AND DosageRemaining>0 AND Completed=0",("@Id",id));
 public List<CareFood> Food(int pet){using var c=Open(pet);using var q=new SqlCommand("SELECT Id,FoodName,ISNULL(Notes,''),AmountGrams,IntervalHours,IntervalMinutes,COALESCE(StartTimestamp,FedAt),LastFedTimestamp,IsCompleted FROM FoodLogs WHERE PetId=@Pet ORDER BY Id DESC",c);q.Parameters.AddWithValue("@Pet",pet);using var r=q.ExecuteReader();var rows=new List<CareFood>();while(r.Read())rows.Add(new(){Id=r.GetInt32(0),Name=r.GetString(1),Notes=r.GetString(2),Grams=r.IsDBNull(3)?0:Convert.ToDouble(r.GetValue(3)),Hours=r.GetInt32(4),Minutes=r.GetInt32(5),StartedAt=ParseDate(r.GetValue(6))??DateTime.Now,LastFedAt=r.IsDBNull(7)?null:ParseDate(r.GetValue(7)),Completed=r.GetBoolean(8)});return rows;}
 public void SaveFood(int pet,CareFood x){if(string.IsNullOrWhiteSpace(x.Name)||x.Name.Length>150||x.Grams<0||x.Hours<0||x.Minutes<0||x.Minutes>59)throw new ArgumentException("Enter a food name, nonnegative amount, and a valid feeding interval.");Execute(pet,x.Id==0?"INSERT INTO FoodLogs(PetId,FoodName,PortionSize,Notes,FedAt,AmountGrams,IntervalHours,IntervalMinutes,StartTimestamp,LastFedTimestamp,IsCompleted,CompletedAt) VALUES(@Pet,@Name,@Portion,@Notes,@Start,@Grams,@Hours,@Minutes,@Start,@Fed,@Done,CASE WHEN @Done=1 THEN SYSDATETIME() ELSE NULL END)":"UPDATE FoodLogs SET FoodName=@Name,PortionSize=@Portion,Notes=@Notes,AmountGrams=@Grams,IntervalHours=@Hours,IntervalMinutes=@Minutes,StartTimestamp=@Start,LastFedTimestamp=@Fed,IsCompleted=@Done,CompletedAt=CASE WHEN @Done=1 THEN ISNULL(CompletedAt,SYSDATETIME()) ELSE NULL END WHERE Id=@Id AND PetId=@Pet",("@Id",x.Id),("@Name",x.Name.Trim()),("@Portion",$"{x.Grams} g"),("@Notes",x.Notes),("@Start",x.StartedAt),("@Grams",x.Grams),("@Hours",x.Hours),("@Minutes",x.Minutes),("@Fed",x.LastFedAt),("@Done",x.Completed));}
 public void Fed(int pet,int id)=>Execute(pet,"UPDATE FoodLogs SET FedAt=SYSDATETIME(),FedDate=SYSDATETIME(),LastFedTimestamp=SYSDATETIME() WHERE Id=@Id AND PetId=@Pet",("@Id",id));
 public void DeleteFood(int pet,int id)=>Execute(pet,"DELETE FROM FoodLogs WHERE Id=@Id AND PetId=@Pet",("@Id",id));
 void Execute(int pet,string sql,params (string Name,object? Value)[] values){using var c=Open(pet);using var q=new SqlCommand(sql,c);q.Parameters.AddWithValue("@Pet",pet);Bind(q,values);q.ExecuteNonQuery();}
 static void Bind(SqlCommand q,params (string Name,object? Value)[] values){foreach(var v in values)q.Parameters.AddWithValue(v.Name,v.Value??DBNull.Value);}
}
public class CareHealth
{
 public int Id{get;set;}public string Type{get;set;}="vital";public string Title{get;set;}="";public string Notes{get;set;}="";public string VetName{get;set;}="";public DateTime RecordDate{get;set;}=DateTime.Now;public DateTime? DueDate{get;set;}public bool Completed{get;set;}public DateTime? DateAdministered{get;set;}public int ValidityInterval{get;set;}public string ValidityUnit{get;set;}="Months";public decimal MedicationIntervalHours{get;set;}public DateTime? TimeStarted{get;set;}public int DosageTotal{get;set;}public int DosageRemaining{get;set;}public DateTime? CheckupDate{get;set;}public string DocumentPaths{get;set;}="";
}
public class CareFood {public int Id{get;set;}public string Name{get;set;}="";public string Notes{get;set;}="";public double Grams{get;set;}public int Hours{get;set;}public int Minutes{get;set;}public DateTime StartedAt{get;set;}=DateTime.Now;public DateTime? LastFedAt{get;set;}public bool Completed{get;set;}}
